name: Excalibur Swordplay CI

on:
  push:
    branches: [master]
  # pullrequest:
  #   branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm

    - run: npm pkg delete scripts.prepare

    - name: Install dependencies
      run: npm install --frozen-lockfile

    - name: Linting
      run: npm run ci:lint

    - name: Typechecking
      run: npm run typecheck

    - name: Tests
      run: npm run ci:test
