name: Excalibur Swordplay CI

on:
  push:
    branches: [master]
  # pullrequest:
  #   branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
          version: 9
          run_install: false

    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: pnpm

    - run: npm pkg delete scripts.prepare

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Linting
      run: pnpm ci:lint

    - name: Typechecking
      run: pnpm typecheck

    - name: Tests
      run: pnpm ci:test
